metric: COCO
num_classes: 4

TrainDataset:
  name: COCODataSet
  image_dir: train
  anno_path: annotations/bbox_train.json
  dataset_dir: dataset/Final_No_Specific_Label
  data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  name: COCODataSet
  image_dir: val
  anno_path: annotations/bbox_val.json
  dataset_dir: dataset/Final_No_Specific_Label
  allow_empty: true

TestDataset:
  name: ImageFolder
  anno_path: annotations/bbox_test.json # also support txt (like VOC's label_list.txt)
  dataset_dir: dataset/Final_No_Specific_Label # if set, anno_path will be 'dataset_dir/anno_path'
